' Gambas module file
PUBLIC text AS String
PUBLIC start_type AS Boolean
PUBLIC pos AS Integer
PUBLIC char AS String
PUBLIC stop_type AS Boolean
PUBLIC is_capslock_on AS Boolean
PUBLIC correct_typing AS Boolean
PUBLIC tuts_number AS Integer
PUBLIC last_open_dir AS String

PUBLIC func_array AS Integer[] = [4100, 4097, 4096, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4134, 4104, 4102, 4112, 4118, 4103, 4113, 4119, 4114, 4115, 4117, 4116, 4133, 4129, 4179, 4131]

PUBLIC SUB reset()
  text = ""
  start_type = ""
  pos = 0
  char = ""
  stop_type = FALSE
  is_capslock_on = FALSE
  correct_typing = FALSE
  tuts_number = 0
END

PUBLIC FUNCTION DirPath(OPTIONAL filePath AS String = "") AS String
  
  DIM filename AS String
  DIM length AS Integer
  DIM result AS String
  
  filename = File.Name(filePath)
  length = RInStr(filePath, filename) - 1
  result = Left(filePath, length)
  RETURN result
  
END
